#############################################################################
# Makefile for building: omasuite
# Generated by qmake (3.1) (Qt 6.11.2)
# Project:  OmaSuite.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile OmaSuite.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORKAUTH_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -pthread -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -pthread -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = omasuite1.0.0
DISTDIR = /home/brett/Projects/OmaSuite/.tmp/omasuite1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) -lsecret-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 /usr/lib/libQt6QuickControls2.so /usr/lib/libQt6Quick.so /usr/lib/libQt6OpenGL.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Qml.so /usr/lib/libQt6NetworkAuth.so /usr/lib/libQt6Network.so /usr/lib/libQt6Sql.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/appcore.cpp \
		src/storage/database.cpp \
		src/storage/secretstore.cpp \
		src/account/account.cpp \
		src/account/accountmanager.cpp \
		src/account/provider.cpp \
		src/mail/mailmodel.cpp \
		src/mail/imapclient.cpp \
		src/mail/smtpclient.cpp \
		src/calendar/calendarmodel.cpp \
		src/calendar/caldavclient.cpp \
		src/contacts/contactmodel.cpp \
		src/contacts/carddavclient.cpp \
		src/tasks/taskmodel.cpp \
		src/net/mimeutils.cpp \
		src/net/icalutils.cpp \
		src/net/vcardutils.cpp \
		src/net/synccontroller.cpp \
		src/net/oauth2manager.cpp \
		src/net/ewsclient.cpp qrc_resources.cpp \
		moc_appcore.cpp \
		moc_database.cpp \
		moc_account.cpp \
		moc_accountmanager.cpp \
		moc_mailmodel.cpp \
		moc_imapclient.cpp \
		moc_smtpclient.cpp \
		moc_calendarmodel.cpp \
		moc_caldavclient.cpp \
		moc_contactmodel.cpp \
		moc_carddavclient.cpp \
		moc_taskmodel.cpp \
		moc_synccontroller.cpp \
		moc_oauth2manager.cpp \
		moc_ewsclient.cpp
OBJECTS       = main.o \
		appcore.o \
		database.o \
		secretstore.o \
		account.o \
		accountmanager.o \
		provider.o \
		mailmodel.o \
		imapclient.o \
		smtpclient.o \
		calendarmodel.o \
		caldavclient.o \
		contactmodel.o \
		carddavclient.o \
		taskmodel.o \
		mimeutils.o \
		icalutils.o \
		vcardutils.o \
		synccontroller.o \
		oauth2manager.o \
		ewsclient.o \
		qrc_resources.o \
		moc_appcore.o \
		moc_database.o \
		moc_account.o \
		moc_accountmanager.o \
		moc_mailmodel.o \
		moc_imapclient.o \
		moc_smtpclient.o \
		moc_calendarmodel.o \
		moc_caldavclient.o \
		moc_contactmodel.o \
		moc_carddavclient.o \
		moc_taskmodel.o \
		moc_synccontroller.o \
		moc_oauth2manager.o \
		moc_ewsclient.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDDockWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		OmaSuite.pro src/appcore.h \
		src/storage/database.h \
		src/storage/secretstore.h \
		src/account/account.h \
		src/account/accountmanager.h \
		src/account/provider.h \
		src/mail/mailmodel.h \
		src/mail/imapclient.h \
		src/mail/smtpclient.h \
		src/calendar/calendarmodel.h \
		src/calendar/caldavclient.h \
		src/contacts/contactmodel.h \
		src/contacts/carddavclient.h \
		src/tasks/taskmodel.h \
		src/net/mimeutils.h \
		src/net/icalutils.h \
		src/net/vcardutils.h \
		src/net/synccontroller.h \
		src/net/oauth2manager.h \
		src/net/ewsclient.h src/main.cpp \
		src/appcore.cpp \
		src/storage/database.cpp \
		src/storage/secretstore.cpp \
		src/account/account.cpp \
		src/account/accountmanager.cpp \
		src/account/provider.cpp \
		src/mail/mailmodel.cpp \
		src/mail/imapclient.cpp \
		src/mail/smtpclient.cpp \
		src/calendar/calendarmodel.cpp \
		src/calendar/caldavclient.cpp \
		src/contacts/contactmodel.cpp \
		src/contacts/carddavclient.cpp \
		src/tasks/taskmodel.cpp \
		src/net/mimeutils.cpp \
		src/net/icalutils.cpp \
		src/net/vcardutils.cpp \
		src/net/synccontroller.cpp \
		src/net/oauth2manager.cpp \
		src/net/ewsclient.cpp
QMAKE_TARGET  = omasuite
DESTDIR       = 
TARGET        = omasuite


first: all
####### Build rules

omasuite:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OmaSuite.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDDockWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		OmaSuite.pro \
		resources.qrc \
		/usr/lib/libQt6QuickControls2.prl \
		/usr/lib/libQt6Quick.prl \
		/usr/lib/libQt6OpenGL.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Qml.prl \
		/usr/lib/libQt6NetworkAuth.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Sql.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile OmaSuite.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDDockWidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltc_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
OmaSuite.pro:
resources.qrc:
/usr/lib/libQt6QuickControls2.prl:
/usr/lib/libQt6Quick.prl:
/usr/lib/libQt6OpenGL.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Qml.prl:
/usr/lib/libQt6NetworkAuth.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Sql.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OmaSuite.pro

qmake_all: FORCE


all: Makefile omasuite

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/appcore.h src/storage/database.h src/storage/secretstore.h src/account/account.h src/account/accountmanager.h src/account/provider.h src/mail/mailmodel.h src/mail/imapclient.h src/mail/smtpclient.h src/calendar/calendarmodel.h src/calendar/caldavclient.h src/contacts/contactmodel.h src/contacts/carddavclient.h src/tasks/taskmodel.h src/net/mimeutils.h src/net/icalutils.h src/net/vcardutils.h src/net/synccontroller.h src/net/oauth2manager.h src/net/ewsclient.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/appcore.cpp src/storage/database.cpp src/storage/secretstore.cpp src/account/account.cpp src/account/accountmanager.cpp src/account/provider.cpp src/mail/mailmodel.cpp src/mail/imapclient.cpp src/mail/smtpclient.cpp src/calendar/calendarmodel.cpp src/calendar/caldavclient.cpp src/contacts/contactmodel.cpp src/contacts/carddavclient.cpp src/tasks/taskmodel.cpp src/net/mimeutils.cpp src/net/icalutils.cpp src/net/vcardutils.cpp src/net/synccontroller.cpp src/net/oauth2manager.cpp src/net/ewsclient.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt6/rcc \
		qml/SetupWizard.qml \
		qml/MainWindow.qml \
		qml/main.qml \
		qml/tasks/TasksView.qml \
		qml/mail/MailView.qml \
		qml/contacts/ContactsView.qml \
		qml/calendar/CalendarView.qml \
		qml/components/ProviderButton.qml \
		qml/components/SidebarButton.qml
	/usr/lib/qt6/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -pthread -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_appcore.cpp moc_database.cpp moc_account.cpp moc_accountmanager.cpp moc_mailmodel.cpp moc_imapclient.cpp moc_smtpclient.cpp moc_calendarmodel.cpp moc_caldavclient.cpp moc_contactmodel.cpp moc_carddavclient.cpp moc_taskmodel.cpp moc_synccontroller.cpp moc_oauth2manager.cpp moc_ewsclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_appcore.cpp moc_database.cpp moc_account.cpp moc_accountmanager.cpp moc_mailmodel.cpp moc_imapclient.cpp moc_smtpclient.cpp moc_calendarmodel.cpp moc_caldavclient.cpp moc_contactmodel.cpp moc_carddavclient.cpp moc_taskmodel.cpp moc_synccontroller.cpp moc_oauth2manager.cpp moc_ewsclient.cpp
moc_appcore.cpp: src/appcore.h \
		src/account/accountmanager.h \
		src/mail/mailmodel.h \
		src/calendar/calendarmodel.h \
		src/contacts/contactmodel.h \
		src/tasks/taskmodel.h \
		src/net/synccontroller.h \
		src/net/oauth2manager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/appcore.h -o moc_appcore.cpp

moc_database.cpp: src/storage/database.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/storage/database.h -o moc_database.cpp

moc_account.cpp: src/account/account.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/account/account.h -o moc_account.cpp

moc_accountmanager.cpp: src/account/accountmanager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/account/accountmanager.h -o moc_accountmanager.cpp

moc_mailmodel.cpp: src/mail/mailmodel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/mail/mailmodel.h -o moc_mailmodel.cpp

moc_imapclient.cpp: src/mail/imapclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/mail/imapclient.h -o moc_imapclient.cpp

moc_smtpclient.cpp: src/mail/smtpclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/mail/smtpclient.h -o moc_smtpclient.cpp

moc_calendarmodel.cpp: src/calendar/calendarmodel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/calendar/calendarmodel.h -o moc_calendarmodel.cpp

moc_caldavclient.cpp: src/calendar/caldavclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/calendar/caldavclient.h -o moc_caldavclient.cpp

moc_contactmodel.cpp: src/contacts/contactmodel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/contacts/contactmodel.h -o moc_contactmodel.cpp

moc_carddavclient.cpp: src/contacts/carddavclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/contacts/carddavclient.h -o moc_carddavclient.cpp

moc_taskmodel.cpp: src/tasks/taskmodel.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/tasks/taskmodel.h -o moc_taskmodel.cpp

moc_synccontroller.cpp: src/net/synccontroller.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/net/synccontroller.h -o moc_synccontroller.cpp

moc_oauth2manager.cpp: src/net/oauth2manager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/net/oauth2manager.h -o moc_oauth2manager.cpp

moc_ewsclient.cpp: src/net/ewsclient.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/brett/Projects/OmaSuite/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/brett/Projects/OmaSuite -I/home/brett/Projects/OmaSuite/src -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/tss2 -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetworkAuth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/net/ewsclient.h -o moc_ewsclient.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/appcore.h \
		src/account/accountmanager.h \
		src/mail/mailmodel.h \
		src/calendar/calendarmodel.h \
		src/contacts/contactmodel.h \
		src/tasks/taskmodel.h \
		src/net/synccontroller.h \
		src/net/oauth2manager.h \
		src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

appcore.o: src/appcore.cpp src/appcore.h \
		src/account/accountmanager.h \
		src/mail/mailmodel.h \
		src/calendar/calendarmodel.h \
		src/contacts/contactmodel.h \
		src/tasks/taskmodel.h \
		src/net/synccontroller.h \
		src/net/oauth2manager.h \
		src/account/provider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appcore.o src/appcore.cpp

database.o: src/storage/database.cpp src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/storage/database.cpp

secretstore.o: src/storage/secretstore.cpp src/storage/secretstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secretstore.o src/storage/secretstore.cpp

account.o: src/account/account.cpp src/account/account.h \
		src/account/provider.h \
		src/storage/secretstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account.o src/account/account.cpp

accountmanager.o: src/account/accountmanager.cpp src/account/accountmanager.h \
		src/account/account.h \
		src/account/provider.h \
		src/storage/database.h \
		src/storage/secretstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountmanager.o src/account/accountmanager.cpp

provider.o: src/account/provider.cpp src/account/provider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o provider.o src/account/provider.cpp

mailmodel.o: src/mail/mailmodel.cpp src/mail/mailmodel.h \
		src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mailmodel.o src/mail/mailmodel.cpp

imapclient.o: src/mail/imapclient.cpp src/mail/imapclient.h \
		src/net/mimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imapclient.o src/mail/imapclient.cpp

smtpclient.o: src/mail/smtpclient.cpp src/mail/smtpclient.h \
		src/net/mimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smtpclient.o src/mail/smtpclient.cpp

calendarmodel.o: src/calendar/calendarmodel.cpp src/calendar/calendarmodel.h \
		src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calendarmodel.o src/calendar/calendarmodel.cpp

caldavclient.o: src/calendar/caldavclient.cpp src/calendar/caldavclient.h \
		src/net/icalutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caldavclient.o src/calendar/caldavclient.cpp

contactmodel.o: src/contacts/contactmodel.cpp src/contacts/contactmodel.h \
		src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contactmodel.o src/contacts/contactmodel.cpp

carddavclient.o: src/contacts/carddavclient.cpp src/contacts/carddavclient.h \
		src/net/vcardutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carddavclient.o src/contacts/carddavclient.cpp

taskmodel.o: src/tasks/taskmodel.cpp src/tasks/taskmodel.h \
		src/storage/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskmodel.o src/tasks/taskmodel.cpp

mimeutils.o: src/net/mimeutils.cpp src/net/mimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimeutils.o src/net/mimeutils.cpp

icalutils.o: src/net/icalutils.cpp src/net/icalutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o icalutils.o src/net/icalutils.cpp

vcardutils.o: src/net/vcardutils.cpp src/net/vcardutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vcardutils.o src/net/vcardutils.cpp

synccontroller.o: src/net/synccontroller.cpp src/net/synccontroller.h \
		src/account/account.h \
		src/account/accountmanager.h \
		src/mail/mailmodel.h \
		src/mail/imapclient.h \
		src/mail/smtpclient.h \
		src/calendar/calendarmodel.h \
		src/calendar/caldavclient.h \
		src/contacts/contactmodel.h \
		src/contacts/carddavclient.h \
		src/tasks/taskmodel.h \
		src/net/oauth2manager.h \
		src/net/ewsclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o synccontroller.o src/net/synccontroller.cpp

oauth2manager.o: src/net/oauth2manager.cpp src/net/oauth2manager.h \
		src/account/account.h \
		src/account/provider.h \
		src/storage/secretstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oauth2manager.o src/net/oauth2manager.cpp

ewsclient.o: src/net/ewsclient.cpp src/net/ewsclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ewsclient.o src/net/ewsclient.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_appcore.o: moc_appcore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appcore.o moc_appcore.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_account.o: moc_account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_account.o moc_account.cpp

moc_accountmanager.o: moc_accountmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountmanager.o moc_accountmanager.cpp

moc_mailmodel.o: moc_mailmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mailmodel.o moc_mailmodel.cpp

moc_imapclient.o: moc_imapclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imapclient.o moc_imapclient.cpp

moc_smtpclient.o: moc_smtpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smtpclient.o moc_smtpclient.cpp

moc_calendarmodel.o: moc_calendarmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calendarmodel.o moc_calendarmodel.cpp

moc_caldavclient.o: moc_caldavclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caldavclient.o moc_caldavclient.cpp

moc_contactmodel.o: moc_contactmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contactmodel.o moc_contactmodel.cpp

moc_carddavclient.o: moc_carddavclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carddavclient.o moc_carddavclient.cpp

moc_taskmodel.o: moc_taskmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskmodel.o moc_taskmodel.cpp

moc_synccontroller.o: moc_synccontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_synccontroller.o moc_synccontroller.cpp

moc_oauth2manager.o: moc_oauth2manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oauth2manager.o moc_oauth2manager.cpp

moc_ewsclient.o: moc_ewsclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ewsclient.o moc_ewsclient.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/qt6/bin || mkdir -p $(INSTALL_ROOT)/usr/lib/qt6/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/lib/qt6/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/qt6/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt6/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

